name: Build and push docker image

on:
  workflow_dispatch:
  push:
    tags:
      - '*'
      
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build big_db_32bit binaries
      env:
        GOARCH: arm
      run: |
        git clone https://github.com/simonvetter/influxdb.git
        cd influxdb
        git checkout origin/1.8.10+big_db_32bit
        mkdir build
        go build -o build/influx_stress cmd/influx_stress/*.go
        go build -o build/influx_tools cmd/influx_tools/*.go
        go build -o build/influx_inspect cmd/influx_inspect/main.go
        go build -o build/influxd cmd/influxd/main.go
        go build -o build/influx cmd/influx/main.go
        cd ..
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Set container version
      run: echo IMG_VERSION=${GITHUB_REF##*\/} >> $GITHUB_ENV
    - name: Build and push Docker image
      id: docker_build
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/arm/v7
        push: true
        tags: ${{ github.repository_owner }}/influxdb-arm32:${{ env.IMG_VERSION }}
        #tags: ghcr.io/${{ github.repository_owner }}/influxdb-arm32:${{ env.IMG_VERSION }}
#         tags: ghcr.io/${{ github.repository_owner }}/influxdb-arm32:${{ steps.get_version.outputs.version }}

